# Connexió a db-aules
spring.datasource.type=org.springframework.jdbc.datasource.DriverManagerDataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db-aules.uji.es:5432/ei102725scm
spring.datasource.username=ei102725scm
spring.datasource.password=ei102725scm
